//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntityUrunEntities1 : DbContext
    {
        public EntityUrunEntities1()
            : base("name=EntityUrunEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Kategori> Table_Kategori { get; set; }
        public virtual DbSet<Table_Musteri> Table_Musteri { get; set; }
        public virtual DbSet<Table_Satis> Table_Satis { get; set; }
        public virtual DbSet<Table_Urun> Table_Urun { get; set; }
        public virtual DbSet<Table_Admin> Table_Admin { get; set; }
    
        public virtual ObjectResult<string> MarkaGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MarkaGetir");
        }
    }
}
