//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Urun()
        {
            this.Table_Satis = new HashSet<Table_Satis>();
        }
    
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public string UrunMarkas { get; set; }
        public Nullable<short> UrunStokSayisi { get; set; }
        public Nullable<decimal> UrunSatisFiyati { get; set; }
        public Nullable<bool> UrunDurum { get; set; }
        public Nullable<int> UrunKategoriId { get; set; }
    
        public virtual Table_Kategori Table_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Satis> Table_Satis { get; set; }
    }
}
