//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Satis
    {
        public int SatisId { get; set; }
        public Nullable<int> SatisUrun { get; set; }
        public Nullable<int> SatisMusteri { get; set; }
        public Nullable<decimal> SatisFiyat { get; set; }
        public Nullable<System.DateTime> SatisTarih { get; set; }
    
        public virtual Table_Musteri Table_Musteri { get; set; }
        public virtual Table_Urun Table_Urun { get; set; }
    }
}
